### ISSUE TITLE
Upgrade to 0.3.0 failed with database error

### ISSUE THREAD

**Issue by adam42a** [H2CK/oidc#112]
I'm on NextCloud 25.0.3 and I just updated to 0.3.0 via the dashboard. I received this message:

An error occurred during the request. Unable to proceed.
Database error when running migration 0007Date20230121172100 for app oidc Migration step 'OCA\OIDCIdentityProvider\Migration\Version0007Date20230121172100' is unknown

It then appeared to install itself properly anyway and still functions properly. Should I run any checks, and if so what do you recommend?

**Comment by adam42a** [comment]
This is what it shows (table name with oc_ prefix):
`MariaDB [carbonc_nc]> desc oc_oidc_group_map
    -> ;
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| client_id | int(11)          | NO   | MUL | NULL    |                |
| group_id  | varchar(256)     | NO   |     | NULL    |                |
+-----------+------------------+------+-----+---------+----------------+
3 rows in set (0.001 sec)

MariaDB [carbonc_nc]> 
`

**Comment by adam42a** [comment]
These are some of the errors I saw in apache.error.log that I don't recognise:
```
[Thu Feb 02 15:47:39.133052 2023] [access_compat:error] [pid 3041150:tid 140453825021696] [client 51.155.201.220:48794] AH01797: client denied by server configuration: /home/carbonc/sites/cloud/data/.ocdata
[Thu Feb 02 15:51:24.514239 2023] [proxy_fcgi:error] [pid 3041089:tid 140453850199808] [client 51.155.201.220:53664] AH01071: Got error 'PHP message: PHP Notice:  Undefined offset: 1 in /home/carbonc/sites/mediawiki/w/extensions/OpenIDConnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php on line 1055'
[Thu Feb 02 15:52:44.392295 2023] [access_compat:error] [pid 3213241:tid 140453900556032] [client 51.155.201.220:44838] AH01797: client denied by server configuration: /home/carbonc/sites/cloud/data/.ocdata
[Thu Feb 02 15:55:50.217461 2023] [access_compat:error] [pid 3041089:tid 140453825021696] [client 51.155.201.220:42964] AH01797: client denied by server configuration: /home/carbonc/sites/cloud/data/.ocdata

```
Nothing else that I can see, although I'm not massively familiar with nextcloud.

**Comment by H2CK** [comment]
Ok. The database table was created successfully. Therefore every thing is fine and there is nothing else to do.

The error you sent is not directly related to the Nextcloud oidc app itself. It seems to be an (database) error from Mediawiki(?)

**Comment by adam42a** [comment]
That's a relief, thanks. You're right, I do use MediaWiki with OIDC, so I'll check out what their problem is with the MediaWiki OIDC extension.

**Comment by gohrner** [comment]
@adam42a: I also got the same (?) migration error while trying to update from 0.2.9 to 0.4.2:

```
Database error when running migration 0007Date20230121172100 for app oidc
Migration step 'OCA\OIDCIdentityProvider\Migration\Version0007Date20230121172100' is unknown
```

The updated failed and I'm stuck at 0.2.9. The table you mentioned was not migrated.

Any ideas? I don't have anything related to mediawiki installed.

**Comment by gohrner** [comment]
Mh, a second upgrade attempt went through... (Before, my Nextcloud instance was stuck in some "some apps need upgrade" limbo...)

**Comment by adam42a** [comment]
As you can read above, the issue was only temporary. It looks like just one of those things.
