### ISSUE TITLE
Nextcloud fails with error "substr() expects parameter 1 to be string, null given"

### ISSUE THREAD

**Issue by fhirter** [H2CK/oidc#12]
```
Caused by TypeError: substr() expects parameter 1 to be string, null given
/var/www/vhosts/velokurierbern.wolkig.ch/www/apps/oidc/lib/Controller/LoginRedirectorController.php - line 210:
substr()
```

Problem seems to be that `$scope` is null [here](https://github.com/H2CK/oidc/blob/master/lib/Controller/LoginRedirectorController.php#L210).

Client is this:
https://github.com/bolsunovskyi/freescout-oauth

**Comment by H2CK** [comment]
It seems that this client does not set the scope, although it should conforming to the OpenID Connect specification.
Anyway the implementation of the oidc app should be robust to handle missing scopes.
With #13 I added a default scope, if it is not delivered from the client.
The will be available in version 0.1.6 soon.

**Comment by fhirter** [comment]
sweet! thanks for the super fast change! will try it out in the next days.

**Comment by fhirter** [comment]
this is working. issue can be closed. thanks!
