### ISSUE TITLE
Upgrade from 0.3.0. to 0.4.2 failed in Nextcloud AIO 4.3.4

### ISSUE THREAD

**Issue by r-hmn** [H2CK/oidc#133]
Hi, i'm writing this in advance of trying to do another attempt.

I just upgraded from AIO 4.2.0 to 4.3.4.
Then went into the apps section and started updating the apps.
Other 4 apps went ok, but during the OIDC update from 0.3.0 to 0.4.2, an error message popped up (i hope it was written to the nextcloud log which i saved).
After that, the complete AIO went into a failsave state, where nextcloud was inoperable, and only a blank screen was accessible which said to perform manual update and the auto-update flag in config.php is disabled and pointing to the manual https://docs.nextcloud.com/server/25/admin_manual/ (which doesn't contain that flag by the same name).

Have you seen this upgrade error before?
What logs would be of interest to investigate? i saved the /data folder containing the log files containing 

- .htaccess
- audit.log
- audit.log.1
- index.html
- nextcloud.log
- update.log 

update.log says;

> Checking connection to appstore
> Appstore is reachable
> Maintenance mode already disabled
> Getting and backing up the status of apps for later, this might take a while...
> Disabling apps before the update in order to make the update procedure more safe. This can take a while...
> deck 1.8.3 disabled
> forms 3.0.3 disabled
> calendar 4.2.1 disabled
> mimetypelist.js is updated
> drawio 2.1.0 disabled
> external 5.0.0 disabled
> tasks 0.14.5 disabled
> maps 0.2.4 disabled
> fileslibreofficeedit 1.1.0 disabled
> polls 4.0.0 disabled
> twofactor_totp 7.0.0 disabled
> No such app enabled: extract
> contacts 5.0.2 disabled
> richdocuments 7.1.0 disabled
> collectives 2.2.1 disabled
> files_mindmap 0.0.27 disabled
> notify_push 0.5.0 disabled
> spreed 15.0.3 disabled
> **oidc 0.2.8 disabled**
> calendar new version available: 4.2.2
> calendar updated
> polls new version available: 4.1.2
> polls updated
> contacts new version available: 5.0.3
> contacts updated
> notify_push new version available: 0.5.2
> notify_push updated
> **oidc new version available: 0.3.0
> oidc updated**
> Initializing nextcloud 25.0.3.2 ...
> Initializing finished

i've now restored a backup, running AIO 4.3.4 and OIDC provider 0.3.0. 
(i've got mediawiki connected using OIDC provider 0.3.0 and it's working)

**Comment by H2CK** [comment]
Please provide any error message you can find in nextcloud.log.

In the past there have been temporary problems reported when modifying the database schema, that a file Migration... is missing. After a second update attempt everything worked as expected. Currently I assume a caching problem.
See https://github.com/H2CK/oidc/issues/112 or https://github.com/H2CK/oidc/issues/111#issuecomment-1421472770

**Comment by r-hmn** [comment]
Thanks for the other info.
Sorry, the errors in the file(s) i have don't go past 7th of feb(?!). i'll have to wait 2 days(because of planning) and try again, and try capture the logs again.

Contrary to [#111](https://github.com/H2CK/oidc/issues/111#issuecomment-1421472770) i can't use git etc. In nextcloud all-in-one docker, there's an "Apps" page for admins, where the OIDC apps shows as installed, and it shows that there's a newer version. One click on that line and it tries to install the new version. Then a popup appears with the text as in #112 initial message.
As i remember from then my whole AIO 4.3.4(nextcloud 25.0.3) went offline, only showing a warning-cloud page about having to do manual configuration. (ill take screenshot next time). i couldnt find a reference in the admin-manual on where to start.

**Comment by H2CK** [comment]
If the error occurs again, you should be able to deactivate or reinstall the app by using the occ command for the AIO image.

In the AIO documentation (https://github.com/nextcloud/all-in-one#how-to-run-occ-commands) you can find a description how to run the occ command. The exact syntax for the command is described here: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#apps-commands

Example: `php occ app:disable oidc` or `php occ app:update oidc`

**Comment by r-hmn** [comment]
ok, i did the upgrade. i first upgraded AIO to 4.4.1
Then updating OIDC from the apps panel (from 0.3.0 to 0.4.2).
Got the error like #112's initial message (only dates were different)
The browser reported from then on 
> Update needed. 
> Please use the command line updated because automatic updating is disabled in the config.php

This page showed up for any NC link.
Via portainer i opened up a console to the `nextcloud-aio-nextcloud` container. i had to open the console as user `www-data` , so that occ commands were accepted (i didn't need sudo, and it didn't accept sudo).
>php occ app:disable oidc
>php occ app:update oidc

After this, a browser showed a login screen again, and NC was accessible again. The OIDC link used by mediawiki is confirmed to work as well.
Thanks👍
