### ISSUE TITLE
Logout does not integrate with mod_auth_openidc

### ISSUE THREAD

**Issue by webermax** [H2CK/oidc#138]
Logging **in** using **mod_auth_openidc** according to the example works pretty well. :sunglasses: 

How would you realize a **logout** / which openid method is implemented (_backchannel_)?

Just linking to the related redirectUri does not work (where to get the _refresh_token_ from), e.g.?

`/protected/redirect_uri?logout=https%3A%2F%2Flocalhost%2Floggedout.html`

...in this case the user is beeing redirected but it does not logout at all (session still holds valid).

**Comment by H2CK** [comment]
It seems that the app is currently not conforming to neither frontchannel nor backchannel logout. I will try to investigate a possible solution.

**Comment by H2CK** [comment]
With version 0.4.3 there is a basic support for RP initiated logout functionality introduced (refresh_token, ... are no longer needed for successful logout).
A successful logout should be possible when just calling `index.php/apps/oidc/logout` (no further parameters needed). If a session is found this session is logged out.
The discovery endpoint additionally announces the attribute `end_session_endpoint`.

Could you please check if it is now possible to logout with mod_auth_openidc using a url like <OIDCRedirectURI>?logout=https%3A%2F%2Fnextcloud.instance%2Fapps%2Foidc%2Flogout

**Comment by webermax** [comment]
Thanks for the updated version 0.4.3.

Unfortunately we now get an nextcloud error page "The server was unable to complete your request.".

The logout occurs, but no redirect to the desired logout page.

**Comment by webermax** [comment]
...the log file says: "Exception: Class "Firebase\JWT\JWT" not found in file '/apps/oidc/lib/Controller/LogoutController.php' line 154"

**Comment by H2CK** [comment]
This bug should be fixed in version 0.4.4.
Please try if it now work for your configuration.

**Comment by webermax** [comment]
...now the log file says:

`Error: require(/apps/oidc/lib/Controller/../../vendor/autoload.php):  Failed to open stream: No such file or directory at  /apps/oidc/lib/Controller/LogoutController.php#28`

**Comment by webermax** [comment]
Digging into it, there is a file in the folder "composer" (not "vendor"):

`/apps/oidc/lib/Controller/../../vendor/autoload.php`

**Comment by H2CK** [comment]
Thanks for your patience. There was an error in the packaging process that the vendor libraries were not included in the final package.
Please try version 0.4.5 of oidc app.

**Comment by webermax** [comment]
The thanks is entirely on the user side; I appreciate the (fast!) development effort.

We now get:

`Error: include(/apps/oidc/vendor/composer/../firebase/php-jwt/src/JWT.php): Failed to open stream: No such file or directory at /lib/composer/composer/ClassLoader.php#571`

`Exception: Class "Firebase\JWT\JWT" not found in file '/apps/oidc/lib/Controller/LogoutController.php' line 158`

(...maybe you could test with a new install on your side before releasing, too?)

**Comment by webermax** [comment]
...there's no **src** folder in the php-jwt directory, but 3 files only:

CHANGELOG.md, LICENSE, README.md

**Comment by webermax** [comment]
When logging out release **0.4.6** gives:

- Exception: Call to a member function get() on null in file '/apps/oidc/lib/Controller/LogoutController.php' line 230
- Error: Undefined property: OCA\OIDCIdentityProvider\Controller\LogoutController::$userManager at /apps/oidc/lib/Controller/LogoutController.php#230

Does it work properly in your sandbox?

**Comment by H2CK** [comment]
Version 0.4.6 had only NC26 compatibility in scope. The remaining bug you found is fixed with version 0.4.7. Please try out if it works in your case also.

**Comment by webermax** [comment]
Thanks for the hint, 0.4.7 works now without throwing errors (Login screen displayed after logout via client)
 – only thing remainig is the URL redirect: How is it intended to work?

**Comment by H2CK** [comment]
You mean the URL the user is redirected after logout? Correct?
If you want to redirect the user to an other URL than the Nextcloud login screen you could provide this URL as post_logout_redirect_uri as defined in the RP-Initiated Logout Standard.
But the app currently does not (yet) support the post_logout_redirect_uri parameter.

**Comment by webermax** [comment]
Yes, we are using **post_logout_redirect_uri** in order to use NC identities transparently.

Are there any plans to support it?

**Comment by H2CK** [comment]
I will try to analyze a possible solution in the next days.

**Comment by H2CK** [comment]
Please checkout version 0.4.8. This version supports post_logout_redirect_uri. Accepted URIs must be configured in advance in the settings.

**Comment by webermax** [comment]
Works **perfectly** - Thank you very much for your efforts! 🎉

(Just took a while to see the **new** dedicated input for the logout URI in the NC admin settings - also it needs to be 1:1 the same string value, e.g. leaving out port numbers...)
