### ISSUE TITLE
Undefined class constant 'CHAR_ALPHANUMERIC'

### ISSUE THREAD

**Issue by fhirter** [H2CK/oidc#14]
on the token endpoint `index.php/apps/oidc/token` we get a error 500 response. Problem seems to be a [missing constant](https://github.com/H2CK/oidc/blob/master/lib/Controller/OIDCApiController.php#L186):
<img width="660" alt="Bildschirmfoto 2022-06-25 um 11 10 26" src="https://user-images.githubusercontent.com/44547220/175766749-135c1961-42d0-41ac-91ec-29a27b2e28d2.png">

is this an issue in the code or a config issue? Or is the client not supplying a correct request?

**Comment by fhirter** [comment]
It seems that this was introduced in v23 of nextcloud: https://github.com/nextcloud/server/commit/3b656446afcac16b53aeb5906cb0d2dd57a23d7e

this contradicts that this module is compatible with nc versions 21-24. Would be nice if this could be changed to work with older nc versions.

**Comment by H2CK** [comment]
Fixed with #15. Version 0.1.7 in the App Store contains the fix.
