### ISSUE TITLE
InvalidTokenException: Token does not exist

### ISSUE THREAD

**Issue by davidbuzzard** [H2CK/oidc#144]
First of all thanks for oidc. We are looking into using oidc for authenticating for [urlaubsverwaltung](https://github.com/urlaubsverwaltung/urlaubsverwaltung). It's a Java app that starts up only if the authentication provider exists, so up to that point setup of both oidc and urlaubsverwaltung appears to work as intended.

But when trying to actually authenticate the response shown on urlaubsverwaltung is:
```
[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized: [no body]
```

Looking in the logs of NextCloud I'm finding following three subsequent entries related to the process:

```
[oidc] Information: Request to Discovery Endpoint.

GET /index.php/apps/oidc/openid-configuration
from *** at 2023-03-14T15:31:46+00:00
```

```
[oidc] Debug: Send redirect response for client 2aNnhawNTtptY3nTwuIJzmGTL4r7naHBEigydj8OePTMdSMGpMMFGuosAMOlz8W9.

GET /index.php/apps/oidc/authorize?response_type=code&client_id=2aNnhawNTtptY3nTwuIJzmGTL4r7naHBEigydj8OePTMdSMGpMMFGuosAMOlz8W9&scope=openid%20profile%20email&state=lDFhP5Jgv--3TVraEIgcFscvT7lPdP-KA64I9-8W5FU%3D&redirect_uri=https://***/login/oauth2/code/oidc
from *** by david at 2023-03-14T15:32:00+00:00
```

```
[no app in context] Debug: OC\Authentication\Exceptions\InvalidTokenException: Token does not exist: token does not exist at <<closure>>

0. /var/www/html/lib/private/Authentication/Token/Manager.php line 133
   OC\Authentication\Token\PublicKeyTokenProvider->getToken("*** sensitive parameters replaced ***")
1. /var/www/html/lib/private/User/Session.php line 523
   OC\Authentication\Token\Manager->getToken("*** sensitive parameters replaced ***")
2. /var/www/html/lib/private/User/Session.php line 436
   OC\User\Session->isTokenPassword("*** sensitive parameters replaced ***")
3. /var/www/html/lib/private/User/Session.php line 575
   OC\User\Session->logClientIn("*** sensitive parameters replaced ***")
4. /var/www/html/lib/base.php line 1114
   OC\User\Session->tryBasicAuthLogin()
5. /var/www/html/lib/base.php line 1036
   OC::handleLogin()
6. /var/www/html/index.php line 36
   OC::handleRequest()

POST /index.php/apps/oidc/token
from *** at 2023-03-14T15:32:00+00:00
```

I'm aware that the last entry is not credited to oidc, but it's the only actual error that is reproducible whenever attempting to authenticate from urlaubsverwaltung. Is that a setting issue, a compatibility issue, or where do we look next? Thanks in advance for any pointer!

**Comment by H2CK** [comment]
The first two requests to the discovery endpoint and the authorization endpoint seem to be successful. But the request to fetch the token does not reach the oidc app. The Nextcloud router seems to misinterpret this request a does not forward it to the app. Instead Nextcloud tries to interpret the request by itself and finds a token of oidc app which is not accepted by the Nextcloud core authentication. That is why a 401 is returned.

Currently I do not know why this happen. Could you set the debug level of the Urlaubsverwaltung App to be more verbose to get more information about the request to fetch the token (e.g. to get header and body)? Maybe this gives a hint what the problem might be. 
Which Nextcloud version are you using?

A further remark:
I found in the documentation of Urlaubsverwaltung the following:

> Es wird erwartet, dass der OIDC Provider im Access Token folgende Attribute enthält: given_name, family_name, email. Die Urlaubsverwaltung fragt deswegen standardmäßig den OIDC Provider mit den Scopes openid,profile und email an. Sollten diese Scopes nicht passen, können sie mit dem Property uv.security.oidc.scopes überschrieben werden.

The claims `given_name` and `family_name` are currently not provided by the oidc app since Nextcloud internally only manages a display name and email address. They're not that level of granularity for `given_name` and `family_name` in Nextcloud. It might be an option to set those claims with e.g. the display name to given_name and leave the family_name empty.

**Comment by davidbuzzard** [comment]
Thank you very much for the detailed response. We use NextCloud 25.0.4 and oidc 0.4.2. Just saw oidc 0.4.3, updated to that and did a retest, no apparent changes unfortunately.

Since `uv.security.oidc.scopes` allows tweaking the scope and `given_name` and `family_name` are part of the `profile` scope I also tried urlaubsverwaltung without it, also no apparent changes unfortunately. I think using the display name to fill given_name and leave the family_name empty sounds like a good solution, but that doesn't appear to be the cause here, does it?

This is what urlaubsverwaltung's debug log looks like:
```
2023-03-16 08:13:57.346 DEBUG 873013 --- [nio-8080-exec-5] o.s.web.client.RestTemplate              : HTTP POST https://***/index.php/apps/oidc/token
2023-03-16 08:13:57.347 DEBUG 873013 --- [nio-8080-exec-5] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2023-03-16 08:13:57.348 DEBUG 873013 --- [nio-8080-exec-5] o.s.web.client.RestTemplate              : Writing [{grant_type=[authorization_code], code=[9ARwInYYMPwaLLyabkrlSycy4xcpbFS9rVGxh6DuAOphKzWeC3X95UTZlsDPs7G973aIio8GwQQ8GLoOikPdjnhvg3G3w0e3w3lpxbw8F7WKpWGSF4hhgexnrcOQGxji], redirect_uri=[https://***/login/oauth2/code/oidc]}] as "application/x-www-form-urlencoded;charset=UTF-8"
2023-03-16 08:13:57.588 DEBUG 873013 --- [nio-8080-exec-5] o.s.web.client.RestTemplate              : Response 401 UNAUTHORIZED
```

**Comment by H2CK** [comment]
It is not 100% clear to me what the problem might be since I am not able to install the software on my side for further tests.

Since the request to fetch the token does not reach the oidc app itself and the request stucks in the Nextcloud core framework I assume that your application might set an Authorization Header or uses Basic Auth to fetch the token.

Due to the Nextcloud framework restrictions it is only possible to use `client_secret_post` (Send client secrets in POST request body) to fetch the access token. Most implementations support this. Please check if the software could be configured to use `client_secret_post` or contact the developer of this app to retrieve the option to configure it in future.

**Comment by davidbuzzard** [comment]
Thanks for the update. Once I find time I'll try to capture the whole communication between urlaubsverwaltung and oidc/Nextcloud. I'll report back once I managed this or get any other valuable info.

**Comment by gotjoshua** [comment]
I think i'm running into something very similar trying to use the oidc app in nextcloud as a provider for login to open project...

```
cloudtamma-opweb-1        | I, [2023-04-29T21:12:24.092356 #44]  INFO -- : (nextcloud) Request phase initiated.
cloudtamma-app-1          | 172.22.0.12 -  29/Apr/2023:21:12:24 +0000 "GET /index.php" 303
cloudtamma-nextcloud-1    | [TRAEFIK-IP] - - [29/Apr/2023:21:12:25 +0000] "GET /apps/oidc/authorize?client_id=FOO-TOKEN-redacted &nonce=eada2379e4ff4d2570c9ca96f2af476c&redirect_uri=https%3A%2F%2Fprojects.cloud.example.tld%2Fauth%2Fnextcloud%2Fcallback&response_type=code&scope=openid%20email%20profile&state= HTTP/1.1" 303 0 "https://projects.cloud.example.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "[CLIENT-IP]"
```
i get a 303 on the authorize get ^


```
cloudtamma-opweb-1        | I, [2023-04-29T21:12:25.168782 #44]  INFO -- : Started GET "/auth/nextcloud/callback?state=&code=[FILTERED]" for [clientIP] at 2023-04-29 21:12:25 +0000
cloudtamma-opweb-1        | I, [2023-04-29T21:12:25.190750 #44]  INFO -- : (nextcloud) Callback phase initiated.
cloudtamma-nextcloud-1    | [TRAEFIK-IP] - FOO-TOKEN-redacted  [29/Apr/2023:21:12:25 +0000] "POST /index.php/apps/oidc/token HTTP/1.1" 401 24 "-" "Rack::OAuth2 (1.21.3) (2.8.3, ruby 3.2.1 (2023-02-08))" "172.21.0.7"
cloudtamma-app-1          | 172.22.0.12 - FOO-TOKEN-redacted  29/Apr/2023:21:12:25 +0000 "POST /index.php" 401
cloudtamma-opweb-1        | F, [2023-04-29T21:12:25.706801 #44] FATAL -- :   
cloudtamma-opweb-1        | Rack::OAuth2::Client::Error ():
```
i get a 401 on the token POST ^


```
Login failed: 'FOO-TOKEN-redacted' 
(Remote IP: '172....')","userAgent":"Rack::OAuth2 (1.21.3) (2.8.3, ruby 3.2.1 (2023-02-08))",
"version":"25.0.6.1","data":{"app":"core"}}
```
i get this in nextcloud.log in the fpm container ^



> the request to fetch the token does not reach the oidc app.

I assume this is confirmed by the nextcloud log indicating `{"app":"core"}`, right?

as there is a traefik proxy for all containers, and an nginx proxy for the nextcloud fpm, i guess there could be some settings needed.   but it seems that the POST is reaching the fpm, but not reaching the oidc app... any ideas?

**Comment by H2CK** [comment]
While building version 0.5.0 I noticed that the token endpoint uses the Nextcloud session even it is not necessary in that case. So I removed the session. Maybe this might fix this problem that you are not able to fetch the token from the app.
Please try version 0.5.0 and give feedback if the current fix might solve the problem.

**Comment by davidbuzzard** [comment]
Hello, thank you for the notice. Unfortunately the three log messages from OP still apply.

Now there are two additional log messages though, reflecting that OIDC didn't receive the token request as you already stated in your first answer.

```
[core] Warning: Login failed: '2aNnhawNTtptY3nTwuIJzmGTL4r7naHBEigydj8OePTMdSMGpMMFGuosAMOlz8W9' (Remote IP: 'xxx')

POST /index.php/apps/oidc/token
from xxx at 2023-05-13T10:40:46+00:00
```

```
[core] Information: Bruteforce attempt from "xxx" detected for action "login".

POST /index.php/apps/oidc/token
from xxx at 2023-05-13T10:40:46+00:00
```

I'm sorry that I haven't been able to create a more thorough capture of the communication involved yet. Once I get to it I'll post it here as promised.

**Comment by davidbuzzard** [comment]
Hello, the best way to get the exact unencrypted traffic I found so far is using mod_dumpio in httpd, so this is the very verbose dump of the incoming request from urlaubsverwaltung and nextcloud's outgoing response (without touching oidc):

[urlaub_dumpio.txt](https://github.com/H2CK/oidc/files/11628126/urlaub_dumpio.txt)

Does this help any? Thanks!
