### ISSUE TITLE
Add app compaitibility for NextCloud 26

### ISSUE THREAD

**Issue by Pammetje** [H2CK/oidc#152]
Please add app  compaitibility for NextCloud 26

**Comment by H2CK** [comment]
Nextcloud 26 support was added with version 0.4.4.
Please try to use Nextcloud 26 with this version.

**Comment by Pammetje** [comment]
OIDC is not working anymore in combination with Apache Guacamole. I get the following error/message "{"message":"CORS requires basic auth"}

**Comment by H2CK** [comment]
Behavior of CORSMiddleware was changed in Nextcloud 26. Therefore a dedicated CORS handling had to be implemented.
Please try with a version >0.4.6 which should provide NC26 compatibility.

**Comment by Pammetje** [comment]
Hi, just updated to 0.4.7 and SSO with Guacamole and NC26 is working again, thanks a lot for all the work
