### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [H2CK/oidc#16]
Hello,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

Thanks :-)

**Comment by H2CK** [comment]
That should be possible and provided the benefits mentioned by you. I try to investigate it in the next days.

**Comment by p-bo** [comment]
Glad to see this implemented, translations are happening already, see: https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c
Many thanks! :-)

**Comment by H2CK** [comment]
Initial version with Transifex translations: [0.1.8](https://github.com/H2CK/oidc/releases/tag/0.1.8)
