### ISSUE TITLE
Not seeing configuration options in Nexcloud 26 after update to version 0.4.8

### ISSUE THREAD

**Issue by Pammetje** [H2CK/oidc#171]
After updating OIDC from version 0.4.7 to 0.4.8 in NextCloud 26.0 I am not seeing the OIDC configuration options anymore under Administration -> Security. Everthing functions ok, but I am not seeing the current config.

**Comment by H2CK** [comment]
I have also an instance with Nextcloud 26 running and still see the config settings when oidc app runs with version 0.4.8 (using Safari and Chrome).

Are there any error messages in the log files or any errors in the console of the browser?
Which browser are you using?

**Comment by Pammetje** [comment]
I do not see the configuration under Administration -> Security. Not with Firefox and also not with a Chrome browser.

**Comment by H2CK** [comment]
Currently I am not possible to reproduce this problem on me side. Could you please upgrade to version 0.4.9 and check if the problem still exists?

**Comment by Pammetje** [comment]
Hi, I updated to OIDC 0.4.9 and also to NC 16.0.1, I still do not see  the OIDC configuration under Administration -> Security. (I also have the apps "Two-Factor TOTP Provider", "Two-Factor WebAuthn" installed, maybe they interfere)

**Comment by Pammetje** [comment]
I am a bit busy at the moment, but when I have time (maybe next week) I will do a complete reinstall of NextCloud 26.01 and OIDC and investigate how I can reproduce the issue.

**Comment by steav** [comment]
@Pammetje I ran in the same issue - I just forgot to `make build`. I only did `make composer`.

**Comment by Pammetje** [comment]
@Steav, What can I do to solve the issue ? I always do a "git clone" in the nextcloud apps folder. I do not use a make build or make composer ?

**Comment by steav** [comment]
git clone is not enough. You then need run `make build` s.t. javascripts are generated.

**Comment by Pammetje** [comment]
@Steav Thanks al a lot

I needed to install npm
I needed to install npm webpack
(I also ran npm audit fix, needed to fix a security vulnerability)
After that I could succesfully run make build, and make composer, and now I indead see the configuration options in the nexcloud admin section again.

I guess if I installed OIDC from the NextCloud app store these steps are not necessary ? 

Again, thanks a lot, this ticket can be closed

**Comment by H2CK** [comment]
You should use the app store or use the artifacts (zip / tgz files) provided in the appropriate release of the oidc app.
By just cloning this repository you will just get the source code. Dependend libraries or final packaged bundles are not included. Therefore it is not possible to use the cloned directory directly without execution of mentioned commands.

**Comment by Pammetje** [comment]
@H2CK thanks for the info, I guess I do not have enough knowledge about all this, but I learned somthing new today
