### ISSUE TITLE
POST support for userinfo endpoint

### ISSUE THREAD

**Issue by davidbuzzard** [H2CK/oidc#191]
We ran across the [OpenID Connect Generic client plugin for WordPress](https://github.com/oidc-wp/openid-connect-generic/pull/435#issuecomment-1244695795) not working with OIDC as provider, which turned out due to it not supporting GET (and OIDC not supporting POST) for the userinfo endpoint. The developer previously refused a simple merge request to fix that referring to the official spec which states that it's up to the **provider** (so OIDC in our case) to support both GET and POST:

https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

> The UserInfo Endpoint MUST support the use of the HTTP GET and HTTP POST methods defined in [RFC 2616](https://openid.net/specs/openid-connect-core-1_0.html#RFC2616) [RFC2616].

> The Client sends the UserInfo Request using either HTTP GET or HTTP POST. 

Any chance support for POST can be realized? Thanks!

**Comment by ssstain** [comment]
There's an issue #199

**Comment by davidbuzzard** [comment]
I can confirm that version 0.5.0 now works fine in this particular setup, thank you!
