### ISSUE TITLE
v0.5.0 users won't log in anymore

### ISSUE THREAD

**Issue by ssstain** [H2CK/oidc#199]
In Discourse with openid-connect plugin users can no longer log in after an update. Nexctloud acts as a provider, Discourse as a client. Had to roll back.

Verbose logging shows on the Discourse side for 0.5.0:

> OIDC Debugging: response status 405 From GET https://.../apps/oidc/userinfo
> (oidc) Authentication failure! invalid_credentials: OAuth2::Error,
> 

For 0.4.9:

> OIDC Debugging: response status 200 From GET https://.../apps/oidc/userinfo
> OIDC Log: Fetched userinfo response ...

What may be the cause? Is that the local settings or the v0.5.0 changes?

**Comment by H2CK** [comment]
Please update to version 0.5.1.

**Comment by ssstain** [comment]
> Please update to version 0.5.1.

Works great now. Thank you.
