### ISSUE TITLE
Token JSON Response expires_in type

### ISSUE THREAD

**Issue by JonasAK** [H2CK/oidc#250]
Hi there!
When generating a token response expires_in should be an integer not a string as defined in [https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse)
Most OpenID clients probably don't care but we experienced an issue with 1Password's implementation which didn't accept strings. Quick fix for us was casting the $expireTime to an integer in the JSON response generated in OIDCApiController.php which is probably not a clean solution.
Have a great day!

**Comment by H2CK** [comment]
Will be fixed with version 0.6.2 available soon.
