### ISSUE TITLE
How mature/secure is this project?

### ISSUE THREAD

**Issue by ninoppp** [H2CK/oidc#26]
How secure is this project? Would you trust it in a production environment as a single point of failure compared to something like keycloak?

**Comment by H2CK** [comment]
The app does not perform the user authentication itself. That is still the task of the Nextcloud server software. The only thing the app does is generating the JWT (after successful authentication) and the oauth token to fetch the JWT. Those JWT Tokens are signed by a public key pair which is generated on the first installation. This public key can be newly generated in the settings.
The public key pair is stored encrypted in the Nextcloud database as well as the generated Tokens, which are used to fetch the JWT. The oauth token generation is identical to the oauth2 implementation of the Nextcloud server.
Additionally it is currently not possible to access any resource on the Nextcloud Server with the tokens of this app or JWT.
So finally the security mainly depends on the Nextcloud server implementation and not on this app.

But anyhow feel free to analyze the app in more detail to find potential security flaws. 

I personally use this app in a production environment.

Your question about single point of failure depends on the setup of your Nextcloud installation. If you use a single node installation for Nextcloud it is the same as if you have a single node keycloak instance.
