### ISSUE TITLE
CI: test with maximum version of NextCloud

### ISSUE THREAD

**Issue by wetneb** [H2CK/oidc#311]
I noticed that the CI runs tests for the oldest compatible NextCloud (currently NextCloud 23). Would it not be nice to run it for the latest version (NextCloud 27) as well? If the test suite is good enough, this could potentially be used to detect incompatibilities with a new version simply by bumping the maximum version in the config file.

**Comment by H2CK** [comment]
Sure might be an option to also execute the test against the latest version.
But the repository currently lacks sufficient tests. The test coverage is pretty low. So as a first step the number of tests should be increased.

**Comment by H2CK** [comment]
With the support for NC 28 also the pipeline was changed to test against lastest supported version. Some further tests were added But still not sufficient.
