### ISSUE TITLE
Cannot connect to Cloudflare as an OIDC provider

### ISSUE THREAD

**Issue by homer1990** [H2CK/oidc#339]
I am getting a: "login failed" from core in the logs.
I have verified multiple times that the secret and client_id are correct.
I tested even with custom length client_id and secret.

Cloudflare doesn't provide detailed logs (can't view secret).

Here is an example from Nextcloud logs:

App: Core
Level: Warning
```javascript
{
  "reqId": "--REDACTED FOR SECURITY--",
  "level": 2,
  "time": "2024-01-15T12:50:18+00:00",
  "remoteAddr": "172.68.62.220",
  "user": "--",
  "app": "core",
  "method": "POST",
  "url": "/apps/oidc/token",
  "message": "Login failed: '--REDACTED FOR SECURITY--' (Remote IP: '172.68.62.220')",
  "userAgent": "--",
  "version": "28.0.1.1",
  "data": {
    "app": "core"
  },
  "id": "--REDACTED FOR SECURITY--"
}
``` 
In cloudflare, all I can find is the log of the Generic OIDC server entry creation:

```javascript
{
    "id": "---REDACTED FOR SECURITY---",
    "type": "oidc",
    "uid": "---REDACTED FOR SECURITY",
    "name": "Nextcloud",
    "version": "673157caf194345d95ae11ef1253e26c",
    "config": {
        "auth_url": "https://nextcloud.xxx.xxx/apps/oidc/authorize",
        "certs_url": "https://nextcloud.xxx.xxx/apps/oidc/jwks",
        "client_id": "---REDACTED FOR SECURITY, MATCHES---",
        "client_secret": "**********************************",
        "pkce_enabled": true,
        "redirect_url": "https://xxx.cloudflareaccess.com/cdn-cgi/access/callback",
        "scopes": [
            "openid",
            "email",
            "profile"
        ],
        "token_url": "https://nextcloud.xxx.xxx/apps/oidc/token"
    },
    "scim_config": {
        "enabled": false,
        "secret": "**********************************",
        "user_deprovision": false,
        "seat_deprovision": false,
        "group_member_deprovision": false
    }
}
```

**Comment by homer1990** [comment]
I tested even with custom length client_id and secret. Cloudflare doesn't provide detailed logs (can't view secret). Here is an example from Nextcloud logs:
App: Core
Level: Warning
Raw log data:
`{
  "reqId": "--REDACTED FOR SECURITY--",
  "level": 2,
  "time": "2024-01-15T12:50:18+00:00",
  "remoteAddr": "172.68.62.220",
  "user": "--",
  "app": "core",
  "method": "POST",
  "url": "/apps/oidc/token",
  "message": "Login failed: '--REDACTED FOR SECURITY--' (Remote IP: '172.68.62.220')",
  "userAgent": "--",
  "version": "28.0.1.1",
  "data": {
    "app": "core"
  },
  "id": "--REDACTED FOR SECURITY--"
}`

**Comment by homer1990** [comment]
In cloudflare, all I can find is the log of the Generic OIDC server entry creation:
```javascript
{
    "id": "---REDACTED FOR SECURITY---",
    "type": "oidc",
    "uid": "---REDACTED FOR SECURITY",
    "name": "Nextcloud",
    "version": "673157caf194345d95ae11ef1253e26c",
    "config": {
        "auth_url": "https://nextcloud.xxx.xxx/apps/oidc/authorize",
        "certs_url": "https://nextcloud.xxx.xxx/apps/oidc/jwks",
        "client_id": "---REDACTED FOR SECURITY, MATCHES---",
        "client_secret": "**********************************",
        "pkce_enabled": true,
        "redirect_url": "https://xxx.cloudflareaccess.com/cdn-cgi/access/callback",
        "scopes": [
            "openid",
            "email",
            "profile"
        ],
        "token_url": "https://nextcloud.xxx.xxx/apps/oidc/token"
    },
    "scim_config": {
        "enabled": false,
        "secret": "**********************************",
        "user_deprovision": false,
        "seat_deprovision": false,
        "group_member_deprovision": false
    }
}
```

**Comment by H2CK** [comment]
The described error should be one of the limitations described at https://github.com/H2CK/oidc#limitations

> Client authentication to fetch token currently only supports the sending of the client credentials in the body. Basic Auth is currently not supported.

Currently all Basic Auth is captured by the Nextcloud core component. Any request of this kind is not passed to the oidc app, since authentication fails.

Could you try to change the configuration on Cloudflare side to send the authention credentials in the body? This is also a standard compliant way to send the credentials and should be supported by most implementations. (in the credentials sometimes called POST credentials or for mod_auth_openid client_secret_post - see https://github.com/H2CK/oidc/wiki/User-Documentation#apache-module-mod_auth_openidc )

**Comment by homer1990** [comment]
<img width="500" alt="image" src="https://github.com/H2CK/oidc/assets/109470676/c890eb17-c297-4cf8-8076-9efdeaba5244">
I don't see how...

Can I achieve this maybe with HAProxy? (PfSense edge).

**Comment by homer1990** [comment]
(If I appear inactive it will be because I will be at work, will remove this comment later).

**Comment by homer1990** [comment]
I think I need to explain the setup a little: Nextcloud Docker | HAProxy(onPfSense) |  Cloudflare.

**Comment by homer1990** [comment]
I tried this Lua script, but still no joy:
```php
core.register_action("convert_basic_auth", { "http-req" }, function(txn)
    -- Check if the request path begins with "/apps/oidc/token"
    local is_oidc_authorize = string.find(txn.sf:path(), "^/apps/oidc/authorize")

    if is_oidc_authorize then
        -- Extract Basic Auth credentials directly from txn
        local auth_header = txn.sf:hdr("authorization")
        local decoded_creds = decode_base64(auth_header:match("Basic%s+(.*)"))

        -- Modify the request for matching ACL
        txn.sf:req_method("POST")
        txn.sf:req_set_header("Content-Type", "application/x-www-form-urlencoded")

        -- Set the payload with credentials in form-urlencoded format
        local credentials = string.match(decoded_creds, "(.*):(.*)")
        local formatted_credentials = "client_id=" .. credentials[1] .. "&client_secret=" .. credentials[2]
        txn.sf:req_set_header("Content-Length", string.len(formatted_credentials))
        txn.sf:req_set_payload(formatted_credentials)

        -- Remove the entire GET query
        txn.sf:req_set_uri(string.match(txn.sf:req_uri(), "([^?]+)"))
    end
end)

function decode_base64(str)
    local b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    local s = str:gsub('.', function(ch)
        if ch == '=' then return '' end
        local b = b64chars:find(ch) - 1
        return string.char(math.floor(b/64*4) + b%64)
    end)
    return s:rep(#str%4 > 1 and 4 - #str%4 or 1)
end
``` Block/

**Comment by H2CK** [comment]
Please have a look at version 0.8.0. With this version Basic Authentication for the token endpoint is supported.

This is realized by providing a "pseudo" user backend to allow Nextcloud core to successfully authenticate the token fetching requests.
