### ISSUE TITLE
Index.php path suffix breaks integration

### ISSUE THREAD

**Issue by 5-tamra** [H2CK/oidc#400]
Hey thank you for providing this extension.

I am trying to use this together with the oidc vaultwarden branch, but authorization fails because of the appended `/index.php` in the issuer url.

```
"Failed to discover OpenID provider: 
Validation error: unexpected issuer URI 'https://nextcloud.example.org/' 
(expected 'https://nextcloud.example.org/index.php')"
```
[I read, that one could add a forwarding on the nextcloud server](https://github.com/H2CK/oidc?tab=readme-ov-file#endpoints), but this is difficult, if the nextcloud is externally hostet.

Also i am wondering, if adding this `index.php`-suffix is in accordance with the [OIDC specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest)

Is there any chance to solve this without the need to configure the redirection?
Either by removing the `index.php`-suffix or by making `/index.php` part of the issuer URL?

**Comment by H2CK** [comment]
If I have a look at your error message from the oidc client software (vaultward) it seems that an issuer is expected, which contains the /index.php path component. But this is not correct. If you would use another IDP like Keycloak there would never be an /index.php.

Could you please provide the output from https://nextcloud.example.org/.well-known/openid-configuration or if this does not work https://nextcloud.example.org/index.php/.well-known/openid-configuration?
In this json output the issuer attribute should never contain index.php.

From my point of view this is an issue in the oidc client implementation (vaultwarden).
Making /index.php part of the issuer is not conforming to the OpenID specification and will not be implemented in the oidc app.

**Comment by 5-tamra** [comment]
Thank you for your answer.
You are right, the issuer should only be `https://nextcloud.example.org`. But according to the specification, the discovery endpoint is defined by appending `/.well-known/openid-configuration` to the issuer URL.
But then, i do not get the `index.php`-suffix into my URL.

Redirecting `https://nextcloud.example.org/.well-known/openid-configuration` to `https://nextcloud.example.org/index.php/.well-known/openid-configuration` causes the openidconnect implementation of rust to break on the (not expected) 301 http response.

```
"Failed to discover OpenID provider: Server returned invalid response: 
HTTP status code 301 Moved Permanently at 
https://nextcloud.example.org/.well-known/openid-configuration"
``` 
Is there any way to have the discovery endpoint natively available at `https://nextcloud.example.org/.well-known/openid-configuration` or is the structure of nextcloud preventing this?
Also do you think, accepting redirects for discovery endpoints is fine and should be fixed in the rust library? I could imagine, that this may have some security impact.

**Comment by H2CK** [comment]
Your question is a general topic about the service discovery of Nextcloud. See also https://docs.nextcloud.com/server/29/admin_manual/issues/general_troubleshooting.html#service-discovery

The described solution also applies to the oidc app (.well-known/openid-configuration).

It seems that the rust library you are using is a bit to strict. It is the first client I see which has trouble with a 301 redirect response for the service discovery. The rust library should be extended to be capable to support 301 redirects. If there are doubts about possible security flaws following redirects, the redirects could be limited to urls to the same host (with different path).

**Comment by 5-tamra** [comment]
Well, that looks like i have to solve it by adding a transparent redirection on the nextcloud server.

Nonetheless, the vaultwarden-oidc maintainer pointed out, that 301 redirection also breaks the spec: `A successful response MUST use the 200 OK HTTP status code and …` ([oidc specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest)), so they probably won't fix it.
So it still would be great, if you find a solution, to make the discovery endpoint available at `https://nextcloud.example.org/.well-known/openid-configuration` just by installing the openidconnect extension, without any additional configuration.

Thank you for your time.
