### ISSUE TITLE
Request for CLI Commands to manage Clients

### ISSUE THREAD

**Issue by ghost** [H2CK/oidc#478]
Hi there :wave: 
I'd like to request basic CLI commands to manage clients
It would provide a way to do that without interacting with the web interface

Something like:
```shell
occ oidc:create <client_name_or_id> <redirect_uris> --encryption="rsa256" --type="confidential"
```

Thank you for considering this feature!

**Comment by H2CK** [comment]
Thank you for your contribution. I will review and merge your PR in the next days.

**Comment by H2CK** [comment]
A new version with the changes will be release soon.
