### ISSUE TITLE
Provide storage quota claim to be used with immich

### ISSUE THREAD

**Issue by hardysim** [H2CK/oidc#503]
I've just set up OIDC in nextcloud to login to immich with my nextcloud user.

This works just fine but it would be great to have the users quota from nextcloud to be set in immich as well. For this, immich asks for a `STORAGE QUOTA CLAIM` named `immich_quota` (can be named freely) in its OAuth configuration page.

Is there a way to get the quota provided via OAuth so immich can "automatically set the user's storage quota to the value of this claim"?

**Comment by H2CK** [comment]
Should be possible to implement. I will check in the next days.

**Comment by H2CK** [comment]
The feature will be available in version 1.1.0 which will be available soon.
For details please read: https://github.com/H2CK/oidc/tree/1.1.0#scopes
