### ISSUE TITLE
Fill given_name and family_name claims

### ISSUE THREAD

**Issue by ThoFrank** [H2CK/oidc#506]
Since version 27 it's possible to expose a [system address book](https://docs.nextcloud.com/server/latest/admin_manual/groupware/contacts.html#system-address-book) in the contacts app. It also somehow populates the first and last name fields of the vcard.

I would like to use oidc to log into [helfertool](https://docs.helfertool.org/admin/configuration.html#openid-connect). But this requires the given_name and family_name to be populated. Do you think this would be possible to use the same approach as in contacts?
Still need to figure out where contacts gets those names from.

**Comment by ThoFrank** [comment]
Yes I know that it's not so straight forward and there are a lot of edge cases. I don't really care about that though. I just would like to have the claims provided with some content. In my use case the names currently all strictly follow the `firstname lastname` scheme.

Therefore I thought It makes sense to potentially reuse what nextcloud itself does.
I guess if the split up names are stored in a database already and not generated on the fly we could use these. And then try to add a way to correct the name entries upstream.

If nextcloud only generates the split up names on the fly your proposed approach is the way to go I would say.

I'll look into this over the holiday period and hopefully come up with something.

**Comment by H2CK** [comment]
Thanks for the PR. I also added this functionality to the ID token (not only the user info endpoint). The functionality is included in version 1.2.0.

**Comment by ThoFrank** [comment]
Great thank you a lot! Merry Christmas
