### ISSUE TITLE
Feature request: support multiple redirect URIs

### ISSUE THREAD

**Issue by darkphoenix** [H2CK/oidc#52]
Correct me if I'm wrong, but it seems you can have only one redirect URI per client ID.  I intend to use this app together with Vouch as an authenticating SSO proxy, and Vouch requires a redirect endpoint on each domain it runs under to get around the limits on cross domain cookies (e.g. auth.example.com, auth.example.org, etc).  Would it be possible to add support for multiple acceptable URIs to be specified per client, as most other OIDC IdP implementations allow?

**Comment by darkphoenix** [comment]
This isn't a super crucial feature, for now I'll probably get by just running one instance per domain, but it would be more convenient to have this option available.

**Comment by H2CK** [comment]
It should be possible to implement support for multiple redirect Uris. I will have a look at it in the next days.

**Comment by H2CK** [comment]
This functionality is added with release [0.2.2](https://github.com/H2CK/oidc/releases/tag/0.2.2)
