### ISSUE TITLE
Scopes don't work with Dovecot

### ISSUE THREAD

**Issue by hirsm** [H2CK/oidc#54]
I use this Nextcloud App to authenticate Roundcube against my Nextcloud instance which works pretty good. Roundcube using the token to authenticate against Dovecot works as well.

What doesn't work is to use scopes. In Roundcube's OAuth2 plugin I entered the scopes I'm interested in. When referring to them in Dovecot (I didn't want everyone to be able to login into Dovecot, only those accounts which are a member of a certain group), Dovecot refuses access stating that there are no scopes affiliated with this token although I entered them in the Roundcube config.

Is this an issue with Roundcube or this plugin?

**Comment by H2CK** [comment]
The scope defines which user specific information is contained in the JWT and provided at the user info endpoint (based on the provided access token).

Currently the following scopes are supported by this app:
`roles`: Adds the claim `roles to the JWT and UserInfo which contains all groups of the user 
`groups`: Adds the claim `groups` to the JWT and UserInfo which contains all groups of the user
`profile`: Adds the claim `name` and `updated_at` to the JWT and UserInfo
`email`: Adds the claim `email` to the JWT and UserInfo

What kind of verification is performed on Dovecot Resource Server side? Couldn't you configure a local JWT validation and check the contained claims (e.g. roles) of the JWT? I have seen that Dovecot usually uses the introspection endpoint. But this is currently not supported by the app.

**Comment by H2CK** [comment]
Closed, due to missing feedback since 2 month. If there is further need for discussion, please reopen the issue.
