### ISSUE TITLE
0.2.2 ParseError: syntax error, unexpected ')', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by ssstain** [H2CK/oidc#65]
Can't add OpenID client.
=== LOG ==
{"reqId":"[skipped]","level":3,"time":"[skipped]","remoteAddr":"[skipped]","user":"[skipped]","app":"index","method":"POST","url":"/apps/oidc/clients","message":"syntax error, unexpected ')', expecting variable (T_VARIABLE)","userAgent":"[skipped]","version":"24.0.6.1","exception":{"Exception":"ParseError","Message":"syntax error, unexpected ')', expecting variable (T_VARIABLE)","Code":0,"Trace":[{"file":"/webserver/nextcloud/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"function":"spl_autoload_call"},{"file":"/webserver/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"__construct","class":"ReflectionClass","type":"->"},{"file":"/webserver/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/webserver/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/webserver/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/webserver/nextcloud/lib/private/AppFramework/App.php","line":159,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/webserver/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/webserver/nextcloud/lib/base.php","line":1030,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/webserver/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/webserver/nextcloud/apps/oidc/lib/Controller/SettingsController.php","Line":186,"CustomMessage":"--"},"id":"[skipped]"}

**Comment by H2CK** [comment]
Fixed with version 0.2.4.
Cause was a little typo which was accepted by PHP Interpreter in Test Environment (embedded PHP Server) but not by the PHP Implementations used by Apache or NGINX.
