### ISSUE TITLE
openssl binary requirement

### ISSUE THREAD

**Issue by assimilat** [H2CK/oidc#7]
Just tried to install, and got a failure due to the openssl command dependency. I poked through the code and the only place I saw the actual openssl binary being called was in the Makefile and the github workflow. Is it safe to remove that dependency line from [appinfo/info.xml?](https://github.com/H2CK/oidc/blob/eeaa9f56afeea1304aecfb9109675e487798b7f7/appinfo/info.xml#L41)

**Comment by H2CK** [comment]
No. The oidc app must generate a key pair.
There is no direct call of openssl from the code itself, but the php function used to generate the key pair requires openssl.
If openssl is not installed it is currently not possible to use the app.

**Comment by assimilat** [comment]
I mean shouldnt the check be for openssl support in php rather than the existance of the openssl binary?

**Comment by H2CK** [comment]
Ok. I understand what you mean. I try to check this in the next days.

**Comment by H2CK** [comment]
After some checks the dependency to openssl is now defined for the php openssl module and no longer as command.
Modification will be available starting from version 0.1.3.
Changes are introduced with PR #8
