### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by mrbreil** [H2CK/oidc#89]
Thank you for this plugin.

Is it also possible to release certain endpoints only for certain nextcloud groups?
That means:
If user "aaa" is a member of the group "gggg" he may log on to client "app2".

**Comment by H2CK** [comment]
I am not sure if got you right.

In general it is already possible with current solution to limit access to client applications using the claims in the JWT. You can set the scope (Default scope: openid profile email roles) in the client configuration to contain `roles` or `groups`.
In the case of `roles` a claim with the name `roles` is contained in the JWT which contains an array containing the group names the user is assigned to. In case the scope contains `groups` a claim `groups` is added to the JWT which contains the user groups.
Therefore it is possible in your client to configure some checks on the claims contained in the JWT. Depending on the client the possible checks on claims in the JWT might be limited.

As alternative the app could be extended to allow the assignment of groups to configured clients. In this case a JWT token will only be provided to the client, if the signing in user is in one of the configured groups. If the user is not in the group list an error page within Nextcloud would be shown.

Does the described extension match your expectation or is your client capable to configure checks on the JWT claims?

**Comment by mrbreil** [comment]
Many Thanks

no, a client is not able to filter by group.

It would also be a small gain in security if the clients only received data from authorized users. ;-)

**Comment by H2CK** [comment]
The functionality to select groups for clients was added with version 0.3.0.
