### ISSUE TITLE
Non-compliant JWT with numeric jti claim

### ISSUE THREAD

**Issue by Orochimarufan** [H2CK/oidc#99]
According to https://www.rfc-editor.org/rfc/rfc7519#section-4.1.7,  "The "jti" value is a case-sensitive string.".

This app directly serializes the AccessToken->id which results in a JSON number value instead of string. Since this isn't covered by the JWT spec, some consumers will choke on this (with errors such as 'json: cannot unmarshal number into Go struct field Alias.jti of type string')

See https://github.com/H2CK/oidc/blob/master/lib/Controller/OIDCApiController.php#L230 and https://github.com/H2CK/oidc/blob/master/lib/Db/AccessToken.php#L63

The quick-fix would be to just stringify the ID before serializing to JSON.

**Comment by H2CK** [comment]
Thank you for reporting this bug.
It is fixed with version 0.2.10. (https://github.com/H2CK/oidc/releases/tag/0.2.10)
